------==========CREANDO LA TABLA USUARIO=============--------------------
CREATE TABLE TBL_USUARIOS
(
	IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_APELLIDOS VARCHAR(50),
	LOGIN VARCHAR(50),
	PASSWORD VARCHAR(50),
	ICONO IMAGE,
	NOMBRE_ICON VARCHAR(MAX),
	CORREO VARCHAR(MAX),
	ROL VARCHAR(MAX)
)
------==========PROCEDIMIENTO PARA INSERTAR USUARIO===========------------
CREATE PROCEDURE SP_INSERTAR_USUARIO
@NOMBRE_APELLIDOS VARCHAR(50),
@LOGIN VARCHAR(50),
@PASSWORD VARCHAR(50),
@ICONO IMAGE,
@NOMBRE_ICON VARCHAR(MAX),
@CORREO VARCHAR(MAX),
@ROL VARCHAR(MAX)
AS
INSERT INTO TBL_USUARIOS VALUES (@NOMBRE_APELLIDOS,@LOGIN,@PASSWORD,@ICONO,@NOMBRE_ICON,@CORREO,@ROL )
GO


---==PROCEDIMIENTO PARA ACTUALIZAR USUARIO========-------------
CREATE PROCEDURE SP_EDITAR_USUARIO
@IDUSUARIO INT,
@NOMBRE_APELLIDOS VARCHAR(50),
@LOGIN VARCHAR(50),
@PASSWORD VARCHAR(50),
@ICONO IMAGE,
@NOMBRE_ICON VARCHAR(MAX),
@CORREO VARCHAR(MAX),
@ROL VARCHAR(MAX)
AS
UPDATE TBL_USUARIOS SET NOMBRE_APELLIDOS=@NOMBRE_APELLIDOS,LOGIN=@LOGIN,PASSWORD=@PASSWORD,
						ICONO=@ICONO,NOMBRE_ICON=@NOMBRE_ICON,CORREO=@CORREO,ROL=@ROL 
FROM TBL_USUARIOS WHERE IDUSUARIO=@IDUSUARIO
GO


----=========PROCEDIMIENTO PARA BUSCAR USUARIO================-----------------
CREATE PROCEDURE SP_BUSCAR_USUARIO
@NOMBRE VARCHAR(50)
AS
SELECT * FROM TBL_USUARIOS
WHERE NOMBRE_APELLIDOS LIKE '%'+@NOMBRE
ORDER BY IDUSUARIO DESC
GO


-----==============PROCEDIMIENTO PARA ELIMINAR USUARIO=================-------------
CREATE PROCEDURE SP_ELIMINAR_USUARIO
@IDUSUARIO int
AS
DELETE FROM TBL_USUARIOS WHERE IDUSUARIO=@IDUSUARIO
GO



